#!/bin/bash

echo "Insert Your Commit"
read var


git add .
git commit -m "${var}"
git push



#commands to clone repository
#git push$ git clone <repo>
#$ touch test
#$ git add test
#$ git commit -m "Initial commit"
#$ git push origin main


